bot = BOT_QQ_NUM
auth_key = "********"
admins = [ADMIN_QQ_NUM]

[modules]
[modules.saucenao]
name = "搜图"
enable = true
groups_enable = []
users_enable = []
admins = []

[modules.nbnhhsh]
name = "能不能好好说话"
enable = true
groups_enable = []
users_enable = []
admins = []

[modules.feed]
name = "RSS订阅"
enable = true
groups_enable = []
users_enable = []
admins = []

[[modules.feed.source]]
name = "游戏打折资讯"
url = "https://rsshub.app/telegram/channel/SteamNy"
groups_enable = []
users_enable = []

[[modules.feed.source]]
name = "明日方舟"
url = "https://rsshub.app/arknights/news"
groups_enable = []
users_enable = []

[modules.autoban]
name = "嘴臭ban人"
enable = true
groups_enable = []
users_enable = []
admins = []

[modules.bilibili]
name = "守护最好的bilibili"
enable = true
groups_enable = []
users_enable = []
admins = []

[modules.setu]
name = "色图来"
enable = true
groups_enable = []
users_enable = []
admins = []
# api.lolicon.app
apikey = ""

[[modules.setu.users]]
# 请求的号码(qq号或群号)
number = 
# 0 不色 1 色 2 抽奖色
r18 = 0

[[modules.setu.groups]]
# 请求的号码(qq号或群号)
number = 
# 0 不色 1 色 2 抽奖色
r18 = 0

[[modules.setu.groups]]
# 请求的号码(qq号或群号)
number = 
# 0 不色 1 色 2 抽奖色
r18 = 0

# 核心模块，进行基本操作
[modules.core]
name = "系统核心"
enable = true
groups_enable = []
users_enable = []
admins = []
about = '''运行UMMCS的试做型中二机娘
目前支持指令
nbnhhsh [包含缩写的句子] -> 不能好好说话
banrule add [正则表达式] -> 添加ban人规则
banrule list -> 列出本群ban人规则
banrule del [ID] -> 移除ban人规则
搜图[图片] -> 以图搜图
图 -> 随机美图
色图 -> 随机色图
[关键字]色图 -> 色图！
about -> 本信息
list_modules -> 列出当前模块列表
clean_data [模块ID] -> 删除模块数据，仅管理员可用。注意删除前先禁用模块'''
