bot = BOT_QQ_NUM
auth_key = "********"
admins = [ADMIN_QQ_NUM]

[modules]
[modules.nbnhhsh]
name = "能不能好好说话"
enable = true
groups_enable = []
users_enable = []
admins = []

[modules.feed]
name = "RSS订阅"
enable = true
groups_enable = []
users_enable = []
admins = []

[[modules.feed.source]]
name = "游戏打折资讯"
url = "https://rsshub.app/telegram/channel/SteamNy"
groups_enable = []
users_enable = []

[[modules.feed.source]]
name = "明日方舟"
url = "https://rsshub.app/arknights/news"
groups_enable = []
users_enable = []

# 核心模块，进行基本操作
[modules.core]
name = "系统核心"
enable = true
groups_enable = []
users_enable = []
admins = []
about = '''运行UMMCS的试做型中二机娘
目前支持指令
nbnhhsh [包含缩写的句子] -> 不能好好说话
about -> 本信息
list_modules -> 列出当前模块列表
clean_data [模块ID] -> 删除模块数据，仅管理员可用。注意删除前先禁用模块'''
